spring:
  datasource:
    url: jdbc:mysql://localhost:3306/author?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: aiyls
    hikari:
      maximum-pool-size: 5